version: '3.7'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/backend
    depends_on:
      - postgresqldb
    links:
      - postgresqldb:postgresqldb
    networks:
      - app-network

  postgresqldb:
    container_name: postgresqldb
    image: "postgres:15-alpine3.17"
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-network
    volumes:
      - ./postgres/scripts/schema.sql:/docker-entrypoint-initdb.d/10-schema.sql

  angular:
    image: node:latest
    container_name: angular_app
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    working_dir: /frontend
    command: >
      sh -c "npm install -g @angular/cli && npm install && ng serve --host 0.0.0.0 --port 4200"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
